language: c

global:
  - EnableNuGetPackageRestore=true 
matrix:
  - MONO_VERSION="3.8.0"

install:
  - sudo add-apt-repository ppa:directhex/monoxide 
  - sudo apt-get update
  - sudo apt-get install mono-devel mono-gmcs nunit-console

script:
  - xbuild build/ci.proj
  - nunit-console ./src/Transformer.Tests/bin/Debug/Transformer.Tests.dll