language: objective-c

env:
 global:
  - EnableNuGetPackageRestore=true 
 matrix:
  - MONO_VERSION="3.12.1"

before_install:
 - wget "http://download.mono-project.com/archive/${MONO_VERSION}/macos-10-x86/MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg"
 - sudo installer -pkg "MonoFramework-MDK-${MONO_VERSION}.macos10.xamarin.x86.pkg" -target /

script:
 - xbuild src/Transformer/Transformer.csproj
# - xbuild src/Transformer.Tests/Transformer.Tests.csproj
# - ./build/nunit.sh src/Transformer.Tests/bin/Debug/Transformer.Tests.dll
